### ISSUE TITLE
Disallow unsupported protocols on user connections

### ISSUE THREAD

**Issue by davidebriani** [edgehog-device-manager/edgehog_device_forwarder#29]
The forwarder supports HTTP requests on the path `https://<host>:<port>/v1/<access_token>/<service_protocol>/<service_port>/<*service_http_path>`.
However, `service_protocol` is not used internally and the parameter can be filled with a random value and still produce valid HTTP requests.

Since the path currently only supports forwarding HTTP requests, and `service_protocol` is assumed to be `http`, it could be mroe meaningful to parse the `service_protocol` param and only allow the value `http`.
This way users will clearly understand the purpose of the path param and the correlation between indicating the `http` service protocol and the fact that the HTTP request performed against the cloud forwarder is forwarded as a corresponding HTTP request against the service on the device.

**Comment by rbino** [comment]
@noaccOS does #31 fixes this? If so you can close the issue

**Comment by rbino** [comment]
Closed by #31
